= Spring Shell image:https://github.com/spring-projects/spring-shell/actions/workflows/ci.yml/badge.svg["CI", link="https://github.com/spring-projects/spring-shell/actions/workflows/ci.yml"]

== Latest news

* December 19, 2025: https://spring.io/blog/2025/12/19/spring-shell-4-0-0-rc1-released[Spring Shell 4.0.0-RC1 available now]
* December 9, 2025: https://spring.io/blog/2025/12/09/spring-shell-4-0-0-m2-released[Spring Shell 4.0.0-M2 is out!]
* October 24, 2025: https://spring.io/blog/2025/10/24/spring-shell-4-0-0-m1-released[Spring Shell 4.0.0-M1 is available!]
* August 4, 2025: https://spring.io/blog/2025/08/04/spring-shell-3-4-1-available[Spring Shell 3.4.1 is now available]

== About Spring Shell

Spring Shell helps you create Spring-powered, production-grade applications targeting the
_CLI_ space. It takes an opinionated view of the Spring platform so that new and existing
users can quickly get the bits they need.

You can use Spring Shell to create stand-alone Java applications that can be started using
`java -jar` or more sophisticated GraalVM native ways to create platform dependant apps.

Our primary goals are:

* Provide a radically faster and widely accessible getting started experience for shell development.
* Be opinionated, but get out of the way quickly as requirements start to diverge from the defaults.

== Installation and Getting Started

Here is a quick teaser of a complete Spring Shell application in Java:

[source,java,indent=0]
----
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.shell.core.command.annotation.Command;

@SpringBootApplication
public class SpringShellApplication {

	@Command
	public String hi() {
		return "hi";
	}

	public static void main(String[] args) {
		SpringApplication.run(SpringShellApplication.class, args);
	}

}
----

Running it as an executable _jar_ in an interactive mode:

[source,bash]
----
$ java -jar demo.jar

shell:>help
Available commands:
Built-In Commands
	clear: Clear the terminal screen
	version: Show version info
	help: Display help about available commands
SpringShellApplication Commands
	hi: N/A

shell:>hi
hi
----

== Tutorials and Sample apps

You can find complete tutorials and sample applications in the `spring-shell-samples` repository:

- https://github.com/spring-projects/spring-shell/tree/main/spring-shell-samples/spring-shell-sample-hello-world[Hello World Spring Shell application]
- https://github.com/spring-projects/spring-shell/tree/main/spring-shell-samples/spring-shell-sample-spring-boot[Hello World Spring Shell application with Spring Boot]
- https://github.com/spring-projects/spring-shell/tree/main/spring-shell-samples/spring-shell-sample-petclinic[Spring Pet Clinic CLI application]
- https://github.com/spring-projects/spring-shell/tree/main/spring-shell-samples/spring-shell-sample-non-interactive[Non-interactive Spring Shell application]

== Getting Help
Are you having trouble with Spring Shell? We want to help!

* Join our GitHub Discussion section and post your question there.

== Reporting Issues
Spring Shell uses GitHub's integrated issue tracking system to record bugs and feature requests.
If you want to raise an issue, please follow the recommendations below:

* Before you log a bug, please search the issue tracker to see if someone has already reported the problem.
* If the issue doesn't already exist, create a new issue.
* Please provide as much information as possible with the issue report. We need to know the Spring Boot and Shell version, operating system, and JVM version you're using.
* If you need to paste code or include a stack trace, please use Markdown's +++```+++ escapes before and after your text.
* If possible, try to create a test case or project that replicates the problem and attach it to the issue.

== Building from Source

The `main` branch contains the work for the next major release `4.0.0`.

Building and running tests:

[source,bash]
----
./mvnw install
----

== Building the Documentation

The documentation is built using Antora and can be run using the Antora Maven plugin.

[source,bash]
----
./mvnw antora -pl spring-shell-docs
----

After running the command, you can view the site for this branch in `spring-shell-docs/target/site`.

== License
Spring Shell is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
