= Spring Shell Docs Build

You're currently viewing the Antora playbook branch.
The playbook branch hosts the docs build that is used to build and publish the production docs site.

The Spring Shell reference docs are built using https://antora.org[Antora].
This README covers how to build the docs in a software branch as well as how to build the production docs site locally.

== Building the Site

To build the entire site invoke the following command:

[source,bash]
----
./mvnw antora
----

You will then be able to view the site at `target/site/index.html`

== Building a Specific Branch

You can build a specific branch and then viewing the branch specific site at `build/site/index.html`.

[source,bash]
----
export BUILD_VERSION=4.0.0-SNAPSHOT
export BUILD_REFNAME=main
./mvnw antora
----

You will then be able to see the site at `build/site/`

[NOTE]
====
If you get the following error, then you must first build the full site and publish it so that a partial builds are supported.
----
FATAL (antora): https://docs.spring.io/spring-shell/reference/site-manifest.json returned response code 404 (Not Found)
----
====
