[[using-shell-components-ui]]
==== UI Components
ifndef::snippets[:snippets: ../../test/java/org/springframework/shell/docs]

Starting from _2.1.x_ there is a new component model which provides
easier way to create higher level user interaction for usual use cases
like asking input in a various forms. These usually are just plain text
input or choosing something from a list.

Templates for build-in components are in classpath under
_org/springframework/shell/component_.

Build-in components generally follow logic:

* Enter run loop for user input
* Generate component related context
* Render runtime status of a component state
* Exit
* Render final status of a component state

[NOTE]
====
<<using-shell-components-flow>> gives better interface defining flow of a
components which better suited for defining interactive command flows.
====

include::using-shell-components-ui-render.adoc[]

include::using-shell-components-ui-stringinput.adoc[]

include::using-shell-components-ui-pathinput.adoc[]

include::using-shell-components-ui-confirmation.adoc[]

include::using-shell-components-ui-singleselect.adoc[]

include::using-shell-components-ui-multiselect.adoc[]
