<if(buildVersion)>
<("Build Version"); format="list-key">: <buildVersion; format="list-value">
<endif>
<if(buildGroup)>
<("Build Group"); format="list-key">: <buildGroup; format="list-value">
<endif>
<if(buildArtifact)>
<("Build Artifact"); format="list-key">: <buildArtifact; format="list-value">
<endif>
<if(buildName)>
<("Build Name"); format="list-key">: <buildName; format="list-value">
<endif>
<if(buildTime)>
<("Build Time"); format="list-key">: <buildTime; format="list-value">
<endif>
<if(gitShortCommitId)>
<("Git Short Commit Id"); format="list-key">: <gitShortCommitId; format="list-value">
<endif>
<if(gitCommitId)>
<("Git Commit Id"); format="list-key">: <gitCommitId; format="list-value">
<endif>
<if(gitBranch)>
<("Git Branch"); format="list-key">: <gitBranch; format="list-value">
<endif>
<if(gitCommitTime)>
<("Git Commit Time"); format="list-key">: <gitCommitTime; format="list-value">
<endif>
