name: Release to Maven Central

on:
  workflow_dispatch:
    inputs:
      buildName:
        description: "Artifactory build name"
        required: true
      buildNumber:
        description: "Artifactory build number"
        required: true

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set Up JFrog CLI
        uses: jfrog/setup-jfrog-cli@68c0efdc951dd2359bbbfa15c48bc67b3ae8e4d6 # v5.2.0
        env:
          JF_ENV_SPRING: ${{ secrets.JF_ARTIFACTORY_SPRING }}
      - name: Download Release Artifacts
        shell: bash
        run: jf rt download --spec .github/release-files-spec.json --spec-vars 'buildname=${{ github.event.inputs.buildName }};buildnumber=${{ github.event.inputs.buildNumber }}'
      - name: Sync to Maven Central
        uses: spring-io/central-publish-action@5ea05c77127404d89c374ac4cd17b6ec6b0e7293 # v0.4.0
        with:
          token: ${{ secrets.CENTRAL_TOKEN_PASSWORD }}
          token-name: ${{ secrets.CENTRAL_TOKEN_USERNAME }}
          timeout: 90m
